name: Build TensorFlow with AVX Optimizations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TensorFlow Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y python3-dev python3-pip build-essential curl
          pip install numpy keras_preprocessing
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | sudo gpg --dearmor -o /usr/share/keyrings/bazel-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install -y bazel

      - name: Clone TensorFlow Repository
        run: |
          git clone https://github.com/tensorflow/tensorflow.git
          cd tensorflow
          git checkout master

      - name: Configure TensorFlow
        run: |
          cd tensorflow
          ./configure

      - name: Build TensorFlow with AVX2, AVX_VNNI, and FMA
        run: |
          cd tensorflow
          bazel build --config=opt \
                      --copt=-march=native \
                      --copt=-mavx2 \
                      --copt=-mfma \
                      --copt=-mavxvnni \
                      //tensorflow/tools/pip_package:build_pip_package_py

      - name: Create TensorFlow Wheel Package
        run: |
          cd tensorflow
          ./bazel-bin/tensorflow/tools/pip_package/build_pip_package_py \
            --output-name tensorflow-custom \
            --project-name tensorflow \
            --platform manylinux2015_x86_64 \
            /tmp/tensorflow_pkg

      - name: Upload TensorFlow Package
        uses: actions/upload-artifact@v4
        with:
          name: tensorflow-wheel
          path: /tmp/tensorflow_pkg/tensorflow-*.whl
